import re
import traceback
from backend.database.database import get_session
from backend.models import CultureStory, Restaurant
from backend.routes.llm_routes import *
import random
from datetime import datetime
from contextlib import contextmanager
from apscheduler.schedulers.background import BackgroundScheduler
from sqlalchemy.orm import Session

def start_scheduler_for_culture_stories():
    scheduler = BackgroundScheduler()
    scheduler.add_job(generate_and_store_food_stories, trigger="interval", days=1)
    scheduler.start()
    print("Scheduler for culture food story summaries started.")

def start_scheduler_for_restaurent_summary():
    scheduler = BackgroundScheduler()
    scheduler.add_job(summarize_all_restaurants, trigger='interval', days=1)
    scheduler.start()
    print("Scheduler for restaurant summaries started.")

@contextmanager
def get_db_session():
    db = get_session()
    try:
        yield db
    finally:
        db.close()

# Clean the summary generated by the LLM
def clean_summary(raw_summary: str) -> str:
    # Remove any <think>...</think> tags and extra whitespace
    cleaned = re.sub(r"<think>.*?</think>", "", raw_summary, flags=re.DOTALL).strip()
    return cleaned

summary_cache = {}

def summarize_all_restaurants():
    """
    Generate summaries for restaurants with no summary in the in-memory cache.
    """
    print("Running restaurant summary generation...")
    #db: Session = next(get_session())
    with get_db_session() as db:
        try:
            restaurants = db.query(Restaurant).all()
            if not restaurants:
                return {"message": "No restaurants found."}

            llm = LLMFactory.get_llm("together")

            summarized = 0

            for restaurant in restaurants:
                if restaurant.restaurant_id in summary_cache:
                    continue  # already summarized

                prompt = (
                    f"Extract a concise, professional short 1–2 sentence summary from the About Us page "
                    f"for a restaurant named '{restaurant.name}'. Focus on its theme, cultural influence, and style.\n\n"
                    f"Summary (1–2 short professional sentences only):"
                )
                try:
                    response = llm.generate(prompt)
                    cleaned = clean_summary(response)
                    summary_cache[restaurant.restaurant_id] = cleaned
                    summarized += 1
                    print(f"Cached summary for: {restaurant.name}")
                except Exception as sub_e:
                    print(f"Error summarizing {restaurant.name}: {sub_e}")

            return {"message": f"{summarized} summaries generated and cached."}

        except Exception as e:
            print("Error during restaurant summary job:", traceback.format_exc())
            return {"error": str(e)}
        finally:
            db.close()

def summarize_restaurant_by_id(restaurant_id: int):
    """
    Generate and save a cultural summary for a specific restaurant.
    """
    print(f"Running summary generation for restaurant_id={restaurant_id}...")

    with get_db_session() as db:
        try:
            restaurant = db.query(Restaurant).filter(Restaurant.restaurant_id == restaurant_id).first()

            if not restaurant:
                return {"error": f"Restaurant ID {restaurant_id} not found."}

            if restaurant.restaurant_id in summary_cache or restaurant.restaurant_description:
                return {"message": f"Summary for '{restaurant.name}' already exists."}

            llm = LLMFactory.get_llm("together")

            prompt = (
                f"Extract a concise, professional short 1–2 sentence summary from the About Us page "
                f"for a restaurant named '{restaurant.name}'. Focus on its theme, cultural influence, and style.\n\n"
                f"Summary (1–2 short professional sentences only):"
            )

            response = llm.generate(prompt)
            cleaned = clean_summary(response)

            # Save to DB
            restaurant.restaurant_description = cleaned
            db.commit()

            # # Save to cache
            # summary_cache[restaurant.restaurant_id] = cleaned

            print(f"Summary saved for: {restaurant.name}")

            return {
                "restaurant_id": restaurant.restaurant_id,
                "name": restaurant.name,
                "summary": cleaned
            }

        except Exception as e:
            print("Error generating summary:", traceback.format_exc())
            return {"error": str(e)}

        finally:
            db.close()

        
def generate_and_store_food_stories():
    with get_db_session() as db:
        try:
            foods = db.query(CultureStory).filter(
                (CultureStory.story == None) | (CultureStory.story == "")
            ).all()

            if len(foods) < 1:
                print("No foods without stories found.")
                return

            selected_foods = random.sample(foods, min(100, len(foods)))

            for food in selected_foods:
                request = FoodFactRequest(
                            food_name=food.food_name,
                            provider="together"  # or "huggingface", depending on your preference
                        )
                response = generate_cultural_fact(request)
                story_summary = response["summary"]  # because your function returns a dict with 'summary'
                story_text = response["fact"]  # because your function returns a dict with 'fact'
                #story_text = generate_cultural_fact()
                cleaned_story_text = clean_summary(story_text)
                cleaned_summary_text = clean_summary(story_summary)
                food.story_summary = cleaned_summary_text
                food.story = cleaned_story_text
                db.commit()

            print("Food stories generated and saved.")

        except Exception as e:
            print("Error during story generation:", str(e))
