services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      - db

  db:
    image: postgres:14
    #restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: