from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy import and_, exists, or_
from sqlalchemy.orm import Session, aliased
import requests, os
from backend.services.yelp_service import YelpService
from backend.database.database import get_session
from backend.auth.auth import get_current_admin_user
from backend.utils.env import GOOGLE_API_KEY
from backend.models import *
from backend.schemas import *
from together import Together
from duckduckgo_search import DDGS
import re
from backend.scheduler import summarize_all_restaurants, summarize_restaurant_by_id

#router = APIRouter(prefix="/places", tags=["places"])
router = APIRouter()
yelp = YelpService()

YELP_API_KEY = os.getenv("YELP_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")

YELP_HEADERS = {"Authorization": f"Bearer {YELP_API_KEY}"}
together = Together(api_key=TOGETHER_API_KEY)

# Add Restaurant
@router.post("/add/", response_model=RestaurantResponse)
def add_restaurant(restaurant: RestaurantCreate, db: Session = Depends(get_session), admin: User = Depends(get_current_admin_user)):
    new_restaurant = Restaurant(**restaurant.dict())
    db.add(new_restaurant)
    db.commit()
    db.refresh(new_restaurant)
    return new_restaurant

# Edit Restaurant
@router.put("/update/{restaurant_id}", response_model=RestaurantResponse)
def update_restaurant(restaurant_id: int, updates: RestaurantUpdate, db: Session = Depends(get_session), admin: User = Depends(get_current_admin_user)):
    restaurant = db.query(Restaurant).filter(Restaurant.restaurant_id == restaurant_id).first()
    if not restaurant:
        raise HTTPException(status_code=404, detail="Restaurant not found")
    
    update_data = updates.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(restaurant, key, value)
    
    # for key, value in updates.dict(exclude_unset=True).items():
    #     setattr(restaurant, key, value)

    db.commit()
    db.refresh(restaurant)
    return restaurant

# Delete Restaurant
@router.delete("/delete/{restaurant_id}")
def delete_restaurant(restaurant_id: int, db: Session = Depends(get_session), admin: User = Depends(get_current_admin_user)):
    restaurant = db.query(Restaurant).filter(Restaurant.restaurant_id == restaurant_id).first()
    if not restaurant:
        raise HTTPException(status_code=404, detail="Restaurant not found")
    
    db.delete(restaurant)
    db.commit()
    return {"message": "Restaurant deleted successfully"}

# @router.get("/story/by_restaurant/{restaurant_id}", response_model=RestaurantStoryResponse)
# def get_restaurant_story(restaurant_id: int, session: Session = Depends(get_session)):
#     story = session.query(RestaurantAbout).filter(RestaurantAbout.restaurant_id == restaurant_id).first()
#     if not story:
#         raise HTTPException(status_code=404, detail="Restaurant story not found")
#     return story

# # Find the restaurant website 
# def find_restaurant_website(query):
#     search_query = f"{query} site:.nz"
#     with DDGS() as ddgs:
#         results = ddgs.text(search_query)
#         for r in results:
#             if "menu" in r.get("href", "") or "about" in r.get("href", ""):
#                 return r["href"]
#         return results[0]["href"] if results else None

# # get the aboute_us page
# def get_about_page_text(url: str) -> str:
#     try:
#         response = requests.get(url, timeout=10)
#         soup = BeautifulSoup(response.content, 'html.parser')
#         texts = soup.find_all(['p', 'h2', 'h3', 'li'])
#         return "\n".join(t.get_text(strip=True) for t in texts if t.get_text(strip=True))
#     except Exception as e:
#         print(f"Failed to extract: {e}")
#         return ""
    
# # Clean the summary generated by the LLM
# def clean_summary(raw_summary: str) -> str:
#     # Remove any <think>...</think> tags and extra whitespace
#     cleaned = re.sub(r"<think>.*?</think>", "", raw_summary, flags=re.DOTALL).strip()
#     return cleaned

# # Summarize the data about the restaurent using LLm
# def summarize_about_page(restaurant_name: str) -> str:
#     """
#     Summarizes a restaurant's About page into a short professional line.
#     """
#     prompt = (
#         f"Extract a concise, professional 1–2 sentence summary from the following About Us page "
#         f"for a restaurant named '{restaurant_name}'. Focus on its theme, cultural influence, and style.\n\n"
#         f"Summary (1–2 professional sentences only):"
#     )

#     try:
#         response = together.chat.completions.create(
#             model="deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
#             messages=[{"role": "user", "content": prompt}],
#             temperature=0.4,
#         )
#         return response.choices[0].message.content.strip()
#     except Exception as e:
#         return f"Failed to summarize: {e}"

#summary_cache = {}

@router.get("/summary/{restaurant_id}", response_model=RestaurantSummary)
def get_restaurant_summary(restaurant_id: int, db: Session = Depends(get_session)):
    restaurant = db.query(Restaurant).filter(Restaurant.restaurant_id == restaurant_id).first()
    if not restaurant:
        raise HTTPException(status_code=404, detail="Restaurant not found")
    return RestaurantSummary(
        restaurant_id=restaurant.restaurant_id,
        name=restaurant.name,
        summary=restaurant.restaurant_description or None
    )

@router.post("/generate-summary/{restaurant_id}", summary="Manually trigger restaurant summary generation by id")
def generate_restaurant_summary_by_id(restaurant_id: int):
    """
    Triggers the same logic used in the daily scheduled job to summarize restaurant descriptions.
    """
    result = summarize_restaurant_by_id(restaurant_id)
    return result

@router.post("/generate-summaries", summary="Manually trigger restaurant summary generation")
def trigger_restaurant_summary_generation():
    """
    Triggers the same logic used in the daily scheduled job to summarize restaurant descriptions.
    """
    result = summarize_all_restaurants()
    return result

# Define reusable filtering logic as a function
def filter_by_all_categories(query, restaurant_model, filters):
    RC = aliased(RestaurantCategory)
    C = aliased(Category)

    for cat_type, value in filters.items():
        if not value:
            continue
        sub = exists().where(
            RC.restaurant_id == restaurant_model.restaurant_id,
            RC.category_id == C.category_id,
            C.name.ilike(f"%{value}%")
        )
        if cat_type in ("cuisine", "special_diet"):
            sub = sub.where(C.type == cat_type)
        elif cat_type == "scene":
            sub = sub.where(C.parent == "scene")
        query = query.filter(sub)
    return query

# --- Helper: Match ANY ---
def get_restaurant_ids_matching_any(db: Session, query: RestaurantBrowseQuery):
    subqueries = []

    if query.cuisine:
        subqueries.append(
            db.query(RestaurantCategory.restaurant_id)
              .join(Category)
              .join(Restaurant)
              .join(Restaurant.location)
              .filter(Location.city.ilike(f"%{query.location}%"))
              .filter(Category.name.ilike(f"%{query.cuisine}%"))
              .filter(Category.type == "cuisine")
        )
    if query.scene:
        subqueries.append(
            db.query(RestaurantCategory.restaurant_id)
              .join(Category)
              .join(Restaurant)
              .join(Restaurant.location)
              .filter(Location.city.ilike(f"%{query.location}%"))
              .filter(Category.name.ilike(f"%{query.scene}%"))
              .filter(Category.parent == "scene")
        )
    if query.special_diet:
        subqueries.append(
            db.query(RestaurantCategory.restaurant_id)
              .join(Category)
              .join(Restaurant)
              .join(Restaurant.location)
              .filter(Location.city.ilike(f"%{query.location}%"))
              .filter(Category.name.ilike(f"%{query.special_diet}%"))
              .filter(Category.type == "special_diet")
        )

    if not subqueries:
        return []

    union_query = subqueries[0]
    for q in subqueries[1:]:
        union_query = union_query.union(q)

    return [r[0] for r in union_query.distinct().all()]

# Browse Restaurants
@router.get("/browse")
def get_restaurants(query: RestaurantBrowseQuery = Depends(),db: Session = Depends(get_session)):
    print(query)
    print(query.match_any)
    if query.match_any:
        print("1")
        matched_ids = get_restaurant_ids_matching_any(db, query)
        # if not matched_ids:
        #     term = query.name or query.cuisine or query.scene or query.special_diet or "restaurant"
        #     print(f"⚡ No DB results (match_any). Fetching from Yelp with term='{term}', location='{query.location}'")
        #     yelp.load_and_store_yelp_data(term=term, location=query.location)
        #     db.expire_all()
        #     matched_ids = get_restaurant_ids_matching_any(db, query)

        #base_query = db.query(Restaurant).filter(Restaurant.restaurant_id.in_(matched_ids))
        base_query = db.query(Restaurant).join(Restaurant.location).filter(
            Location.city.ilike(f"%{query.location}%"))
        
        if query.name:
            base_query = base_query.filter(Restaurant.name.ilike(f"%{query.name}%"))

        filters = {
            "cuisine": query.cuisine,
            "scene": query.scene,
            "special_diet": query.special_diet
        }
        base_query = filter_by_all_categories(base_query, Restaurant, filters)
        #print(base_query)

    # Match ALL mode (default)
    else:
        print("2")
        base_query = db.query(Restaurant).join(Restaurant.location).filter(
            Location.city.ilike(f"%{query.location}%")
        )

        if query.name:
            base_query = base_query.filter(Restaurant.name.ilike(f"%{query.name}%"))

        filters = {
            "cuisine": query.cuisine,
            "scene": query.scene,
            "special_diet": query.special_diet
        }

        cuisine_filters = {
            "cuisine": query.cuisine
        }

        scene_filters = {
            "scene": query.scene
        }

        diet_filters = {
            "special_diet": query.special_diet
        }

        if query.cuisine:
            base_query = filter_by_all_categories(base_query, Restaurant, cuisine_filters)

        if query.scene:
            base_query = filter_by_all_categories(base_query, Restaurant, scene_filters) 

        if query.special_diet:
            base_query = filter_by_all_categories(base_query, Restaurant, diet_filters) 

        restaurants = base_query.distinct().all()
        if not restaurants:
            term = query.name or query.cuisine or query.scene or query.special_diet or "restaurant"
            print(f"⚡ No DB results (match_all). Fetching from Yelp with term='{term}', location='{query.location}'")
            yelp.load_and_store_yelp_data(term=term, location=query.location)
            db.expire_all()

            # base_query = db.query(Restaurant).join(Restaurant.location).filter(
            #     Location.city.ilike(f"%{query.location}%")
            base_query = db.query(Restaurant).join(Restaurant.location).join(Restaurant.operating_hours).filter(
                Location.city.ilike(f"%{query.location}%")
            )
            if query.name:
                base_query = base_query.filter(Restaurant.name.ilike(f"%{query.name}%"))

            base_query = filter_by_all_categories(base_query, Restaurant, filters)

    #restaurants = base_query.distinct().all()
    restaurants = base_query.all()

    return [
        {
            "id": r.restaurant_id,
            "alias": r.alias,
            "name": r.name,
            "image_url": r.image_url,
            "is_closed": r.is_closed,
            "url": r.url,
            "review_count": r.review_count,
            #"categories": r.categories,
            "categories": [
                {"alias": c.alias, "title": c.name}
                for c in r.categories
            ] if r.categories else [],
            "rating": r.rating,
            "coordinates": {
                "latitude": r.latitude,
                "longitude": r.longitude
            },
            "transactions": None,
            "location": {
                "address1": r.location.address1 if r.location else None,
                "address2": r.location.address2 if r.location else None,
                "address3": r.location.address3 if r.location else None,
                "city": r.location.city if r.location else None,
                "zip_code": r.location.zip_code if r.location else None,
                "country": r.location.country if r.location else None,
                "state": r.location.state if r.location else None,
                "display_address": [
                    r.location.display_address if r.location else None
                ]
            },
            "phone": r.phone,
            "display_phone": r.display_phone,
            "distance": r.distance,
            "business_hours":[
                {
                    "open": [
                        {
                            "day": oh.day_of_week,
                            "start": oh.open_time,
                            "end": oh.close_time,
                            "is_overnight": oh.is_overnight
                        }
                        for oh in (r.location.operating_hours if r.location and r.location.operating_hours else [])
                    ],
                    "hours_type": "REGULAR",
                    "is_open_now": False
                }
            ],
            "attributes": r.attributes if r.attributes else None
        }
        for r in restaurants
    ]

    # return [
    #     {
    #         "restaurant_id": r.restaurant_id,
    #         "name": r.name,
    #         "city": r.location.city if r.location else None,
    #         "latitude": r.latitude,
    #         "longitude": r.longitude,
    #         "categories": [c.name for c in r.categories],
    #     }
    #     for r in restaurants
    # ]


def normalize_yelp(business):
    return {
        "id": business.get("id"),
        "name": business.get("name"),
        "alias": business.get("alias"),
        "image_url": business.get("image_url"),
        "is_closed": business.get("is_closed"),
        "url": business.get("url"),
        "review_count": business.get("review_count"),
        "categories": business.get("categories"),
        "rating": business.get("rating"),
        "coordinates": business.get("coordinates"),
        "transactions": business.get("transactions"),
        "location": business.get("location"),
        "phone": business.get("phone"),
        "display_phone": business.get("display_phone"),
        "distance": business.get("distance"),
        "business_hours": None,
        "attributes": None
    }

def normalize_google(place):
    return {
        "id": place.get("place_id"),
        "name": place.get("name"),
        "alias": None,
        "image_url": None,
        "is_closed": None,
        "url": None,
        "review_count": None,
        "categories": [{"alias": place.get("types", [])[0], "title": place.get("types", [])[0]}] if place.get("types") else [],
        "rating": place.get("rating"),
        "coordinates": {
            "latitude": place["geometry"]["location"]["lat"],
            "longitude": place["geometry"]["location"]["lng"]
        },
        "transactions": None,
        "location": {
            "address1": place.get("vicinity"),
            "display_address": [place.get("vicinity")]
        },
        "phone": None,
        "display_phone": None,
        "distance": None,
        "business_hours": None,
        "attributes": None
    }

# Get Restaurant by ID
@router.get("/browse/{restaurant_id}")
def get_restaurant_by_id(
    restaurant_id: int,
    db: Session = Depends(get_session)
):
    restaurant = db.query(Restaurant).join(Restaurant.location).join(Restaurant.operating_hours).filter(Restaurant.restaurant_id == restaurant_id).first()
    if not restaurant:
        raise HTTPException(status_code=404, detail="Restaurant not found")
    #return restaurant
    return{
            "restaurant_id": restaurant.restaurant_id,
            "alias": restaurant.alias,
            "name": restaurant.name,
            "image_url": restaurant.image_url,
            "is_closed": restaurant.is_closed,
            "url": restaurant.url,
            "review_count": restaurant.review_count,
            #"categories": r.categories,
            "categories": [
                {"alias": c.alias, "title": c.name}
                for c in restaurant.categories
            ] if restaurant.categories else [],
            "rating": restaurant.rating,
            "coordinates": {
                "latitude": restaurant.latitude,
                "longitude": restaurant.longitude
            },
            "transactions": None,
            "location": {
                "address1": restaurant.location.address1 if restaurant.location else None,
                "address2": restaurant.location.address2 if restaurant.location else None,
                "address3": restaurant.location.address3 if restaurant.location else None,
                "city": restaurant.location.city if restaurant.location else None,
                "zip_code": restaurant.location.zip_code if restaurant.location else None,
                "country": restaurant.location.country if restaurant.location else None,
                "state": restaurant.location.state if restaurant.location else None,
                "display_address": [
                    restaurant.location.display_address if restaurant.location else None
                ]
            },
            "phone": restaurant.phone,
            "display_phone": restaurant.display_phone,
            "distance": restaurant.distance,
            "business_hours":[
                {
                    "open": [
                        {
                            "day": oh.day_of_week,
                            "start": oh.open_time,
                            "end": oh.close_time,
                            "is_overnight": oh.is_overnight
                        }
                        for oh in (restaurant.location.operating_hours if restaurant.location and restaurant.location.operating_hours else [])
                    ],
                    "hours_type": "REGULAR",
                    "is_open_now": False
                }
            ],
            "attributes": restaurant.attributes if restaurant.attributes else None
        }

# @router.get("/json/yelp/{term}/{location}")
# def get_yelp_json(term: str, location: str):
#     # Normalize filename
#     location_sanitized = location.replace(" ", "_")
#     filename = f"yelp_{term}_{location_sanitized}.json"
#     file_path = os.path.join(os.path.dirname(__file__), "..", "data", filename)

#     if not os.path.exists(file_path):
#         raise HTTPException(status_code=404, detail="JSON file not found")

#     return FileResponse(path=file_path, filename=filename, media_type="application/json")

# @router.get("/add_data_by_location")
# def fetch_yelp_data(location: str = Query(...), cuisine: str = Query("restaurants")):
#     yelp = YelpService()
#     yelp.load_and_store_yelp_data(location=location, cuisine=cuisine)
#     return {"message": f"Yelp data for {cuisine} in {location} stored successfully."}

@router.get("/fetch/data_by_location")
def fetch_all_yelp_restaurants(location: str = "Auckland"):
    cuisines = ["Maori", "Indian", "Japanese", "Thai", "Italian", "Mexican", "Chinese", "Greek", "French", "Turkish", "Vietnamese", "Sri Lankan", "Korean", "Spanish", "Malaysian", "Indonesian", "Filipino", "Pakistani", "Bangladeshi", "Middle Eastern"]
    for cuisine in cuisines:
        print(f"Fetching {cuisine} restaurants in {location}...")
        yelp.load_and_store_yelp_data(term=cuisine, location=location)
    return {"status": f"Fetched data for multiple cuisines in {location}"}